name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Deploy to Hugging Face
        uses: peaceiris/actions-huggingface@v4
        with:
          huggingface_token: ${{ secrets.HF_TOKEN }}
          repository: "Usman396/Test"
          action-type: "space"
          space-sdk: "gradio"
          space-hardware: "cpu-basic"
          directory: "."